"use strict"

const uuidv4 = require("uuid/v4");

module.exports = {
	data: [{
            name: "Baseball Caps",
            path: "/baseball-caps/",
            subCategoryId: 3,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Beanies",
            path: "/beanies/",
            subCategoryId: 3,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Belts",
            path: "/belts/",
            subCategoryId: 3,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Gloves",
            path: "/gloves/",
            subCategoryId: 3,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Scarves",
            path: "/scarves/",
            subCategoryId: 3,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Boxers",
            path: "/boxers/",
            subCategoryId: 2,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Vests",
            path: "/vests/",
            subCategoryId: 2,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Blazers",
            path: "/blazers/",
            subCategoryId: 1,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Hoodies",
            path: "/hoodies/",
            subCategoryId: 1,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Jackets",
            path: "/jackets/",
            subCategoryId: 1,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Shirts",
            path: "/shirts/",
            subCategoryId: 1,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Socks",
            path: "/socks/",
            subCategoryId: 1,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Sweaters",
            path: "/sweaters/",
            subCategoryId: 1,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Trench Coat",
            path: "/trench-coat/",
            subCategoryId: 1,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "T-shirts",
            path: "/t-shirts/",
            subCategoryId: 1,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Casual Pants",
            path: "/casual-pants/",
            subCategoryId: 4,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Jeans",
            path: "/jeans/",
            subCategoryId: 4,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Shorts",
            path: "/shorts/",
            subCategoryId: 4,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Sweatpants",
            path: "/sweatpants/",
            subCategoryId: 4,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Islamic Hat",
            path: "/islamic-hat/",
            subCategoryId: 5,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Kanzu",
            path: "/kanzu/",
            subCategoryId: 5,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Prayer Rug",
            path: "/prayer-rug/",
            subCategoryId: 6,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Caps & Hats",
            path: "/caps-hats/",
            subCategoryId: 7,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Eyewear & Accessories",
            path: "/eyewear-accessories/",
            subCategoryId: 7,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Bra Sets",
            path: "/bra-sets/",
            subCategoryId: 8,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Cardigans",
            path: "/cardigans/",
            subCategoryId: 8,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Jumpsuits",
            path: "/jumpsuits/",
            subCategoryId: 8,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Women's Sets",
            path: "/women-sets/",
            subCategoryId: 8,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "T-Shirts & Tops",
            path: "/t-shirts-tops/",
            subCategoryId: 8,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Wedding Accessories",
            path: "/wedding-accessories/",
            subCategoryId: 9,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Bridesmaid Dress",
            path: "/bridesmaid-dress/",
            subCategoryId: 9,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Wedding Dress",
            path: "/wedding-dress/",
            subCategoryId: 9,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Women Socks",
            path: "/women-socks/",
            subCategoryId: 10,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Tops",
            path: "/tops/",
            subCategoryId: 10,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Abaya",
            path: "/abaya/",
            subCategoryId: 11,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Buibui",
            path: "/buibui/",
            subCategoryId: 11,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Hijab",
            path: "/hijab/",
            subCategoryId: 11,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Leggings",
            path: "/leggings/",
            subCategoryId: 12,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Lingerie",
            path: "/lingerie/",
            subCategoryId: 12,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Baby Boy Clothing",
            path: "/baby-boy-clothing/",
            subCategoryId: 13,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Baby Girl Clothing",
            path: "/baby-girl-clothing/",
            subCategoryId: 13,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Bath Toys",
            path: "/bath-toys/",
            subCategoryId: 14,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Baby Dolls",
            path: "/baby-dolls/",
            subCategoryId: 14,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Musical Toys",
            path: "/musical-toys/",
            subCategoryId: 14,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Baby Creams",
            path: "/baby-creams/",
            subCategoryId: 15,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Baby Towels",
            path: "/baby-towels/",
            subCategoryId: 15,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Diaper Bags",
            path: "/diaper-bags/",
            subCategoryId: 16,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Disposable Diapers",
            path: "/disposable-diapers/",
            subCategoryId: 16,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Wipes",
            path: "/wipes/",
            subCategoryId: 16,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Bottle Feeding",
            path: "/bottle-feeding/",
            subCategoryId: 17,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Breast Feeding Pumps",
            path: "/breast-feeding-pumps/",
            subCategoryId: 17,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Burp Clothes",
            path: "/burp-clothes/",
            subCategoryId: 17,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Chargers & Adapters",
            path: "/chargers-adapters/",
            subCategoryId: 18,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Phone Batteries",
            path: "/phone-batteries/",
            subCategoryId: 18,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Phone Covers",
            path: "/phone-covers/",
            subCategoryId: 18,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Powerbanks",
            path: "/powerbanks/",
            subCategoryId: 18,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Screen Protectors",
            path: "/screen-protectors/",
            subCategoryId: 18,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Selfie Sticks",
            path: "/selfie-sticks/",
            subCategoryId: 18,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Smart Watches",
            path: "/smart-watches/",
            subCategoryId: 18,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Feauture Phone",
            path: "/feature-phone/",
            subCategoryId: 19,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Iphones",
            path: "/iphones/",
            subCategoryId: 19,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Smartphones",
            path: "/smartphones/",
            subCategoryId: 19,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Ipads",
            path: "/ipads/",
            subCategoryId: 20,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Kids Tablets",
            path: "/kids-tablets/",
            subCategoryId: 20,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Tablet Accessories",
            path: "/tablet-accessories/",
            subCategoryId: 20,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Htc",
            path: "/htc/",
            subCategoryId: 21,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Infinix",
            path: "/infinix/",
            subCategoryId: 21,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Lenovo",
            path: "/lenovo/",
            subCategoryId: 21,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Oppo",
            path: "/oppo/",
            subCategoryId: 21,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Samsung",
            path: "/samsung/",
            subCategoryId: 21,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Tecno",
            path: "/tecno/",
            subCategoryId: 21,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Gaming Laptops",
            path: "/gaming-laptops/",
            subCategoryId: 22,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Ultraslim Laptops",
            path: "/ultraslim-laptops/",
            subCategoryId: 22,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Modems",
            path: "/modems/",
            subCategoryId: 23,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Routers",
            path: "/routers/",
            subCategoryId: 23,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Printers",
            path: "/printers/",
            subCategoryId: 24,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Scanners",
            path: "/scanners/",
            subCategoryId: 24,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "CPUs",
            path: "/cpus/",
            subCategoryId: 25,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Motherboards",
            path: "/motherboards/",
            subCategoryId: 25,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Keyboards",
            path: "/keyboards/",
            subCategoryId: 25,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Mouse",
            path: "/mouse/",
            subCategoryId: 25,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Alarms & Sensors",
            path: "alarms-sensors",
            subCategoryId: 26,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "HDD",
            path: "/hhd/",
            subCategoryId: 27,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "SSD",
            path: "/ssd/",
            subCategoryId: 27,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Home Furniture",
            path: "/home-furniture/",
            subCategoryId: 28,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Office Furniture",
            path: "/office-furniture/",
            subCategoryId: 28,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Flower Pots",
            path: "/flower-pots/",
            subCategoryId: 29,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Watering Kits",
            path: "/watering-kits/",
            subCategoryId: 29,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Paintings",
            path: "/paintings/",
            subCategoryId: 30,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Wall Clocks",
            path: "/wall-clocks/",
            subCategoryId: 30,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Wall Stickers",
            path: "/wall-stickers/",
            subCategoryId: 30,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Beddings",
            path: "/beddings/",
            subCategoryId: 31,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Curtains",
            path: "/curtains/",
            subCategoryId: 31,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Cushions",
            path: "/cushions/",
            subCategoryId: 31,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Sweepers & Mops",
            path: "/sweepers-mops/",
            subCategoryId: 32,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Umbrellas",
            path: "/umbrellas/",
            subCategoryId: 32,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Drinkware",
            path: "/drinkware/",
            subCategoryId: 33,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Kitchen Accessories",
            path: "/kitchen-accessories/",
            subCategoryId: 33,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Cuff Links",
            path: "/cuff-links/",
            subCategoryId: 34,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Sports Watches",
            path: "/sports-watches/",
            subCategoryId: 35,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Bridal Jewellery",
            path: "/bridal-jewellery/",
            subCategoryId: 36,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Bracelet Watches",
            path: "/bracelet-watches/",
            subCategoryId: 37,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Bicycle",
            path: "/bicycle/",
            subCategoryId: 38,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Bicycle Accessories",
            path: "/bicycle-accessories/",
            subCategoryId: 38,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Jerseys",
            path: "/jerseys/",
            subCategoryId: 39,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Pants",
            path: "/pants/",
            subCategoryId: 39,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Shorts",
            path: "/shorts/",
            subCategoryId: 39,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Sports Bags",
            path: "/sports-bags/",
            subCategoryId: 39,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Bikini",
            path: "/bikini/",
            subCategoryId: 40,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Children Swimwear",
            path: "/children-swimwear/",
            subCategoryId: 40,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Men's Swimwear",
            path: "/men-swimwear/",
            subCategoryId: 40,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Car Electronics",
            path: "/car-electronics/",
            subCategoryId: 41,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Replacement Parts",
            path: "/replacement-parts/",
            subCategoryId: 41,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Batteries",
            path: "/batteries/",
            subCategoryId: 42,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Chargers",
            path: "/chargers/",
            subCategoryId: 42,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Projectors",
            path: "/projectors/",
            subCategoryId: 43,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Televisions",
            path: "/televisions/",
            subCategoryId: 43,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Digital Cameras",
            path: "/digital-cameras/",
            subCategoryId: 44,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Playstations",
            path: "/playstations/",
            subCategoryId: 45,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }, {
            name: "Game Controllers",
            path: "/game-contollers/",
            subCategoryId: 45,
            sku: uuidv4(),
            createdAt: new Date(),
            updatedAt: new Date(),
        }]
}